import { Fade } from "react-awesome-reveal";

export default function Utility() {
  return (
    <div class="bg-green-50 relative isolate overflow-hidden">
      <div class="mx-auto max-w-7xl px-6 sm:px-8 lg:px-24 bg-gray-900 py-24 rounded-2xl">
        <svg
          viewBox="0 0 1024 1024"
          class="absolute left-1/2 top-1/2 -z-10 h-[64rem] w-[64rem] -translate-x-1/2 [mask-image:radial-gradient(closest-side,white,transparent)] opacity-50"
          aria-hidden="true"
        >
          <circle
            cx="512"
            cy="512"
            r="512"
            fill="url(#827591b1-ce8c-4110-b064-7cb85a0b1217)"
            fillOpacity="0.7"
          ></circle>
          <defs>
            <radialGradient id="827591b1-ce8c-4110-b064-7cb85a0b1217">
              <stop stopColor="#22c55e"></stop>
              <stop offset="1" stopColor="#15803d"></stop>
            </radialGradient>
          </defs>
        </svg>
        <div class="mx-auto max-w-2xl lg:mx-0">
          <h2 class="text-3xl lg:text-4xl font-display text-green-50">
            <span class="text-green-600">$SEILOR </span>
            utility & The governance token of Kryptonite
          </h2>
        </div>
        <div className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-8 text-base leading-7 sm:grid-cols-2 lg:mx-0 lg:max-w-none lg:gap-x-16 text-green-50/80">
          <Fade cascade triggerOnce={true} damping={0.1}>
            <div class="flex flex-row mt-6 text-lg space-x-4">
              <div class="text-green-500">-</div>
              <p class="">
                <span class="text-green-50">Governance participation.</span>{" "}
                SEILOR holders can participate in platform governance, including
                voting rights and the ability to propose changes
              </p>
            </div>
            <div class="flex flex-row mt-6 text-lg space-x-4">
              <div class="text-green-500">-</div>
              <p class="">
                <span class="text-green-50">Value capture.</span> SEILOR holders
                can share in the value generated by the Kryptonite Protocol,
                such as fee distributions and other protocol revenues
              </p>
            </div>
            <div class="flex flex-row mt-6 text-lg space-x-4">
              <div class="text-green-500">-</div>
              <p class="">
                <span class="text-green-50">Platform privileges.</span> SEILOR
                holders are entitled to various privileges provided by the
                platform, such as access to exclusive events, airdrops, and
                other incentive programs
              </p>
            </div>
            <div class="flex flex-row mt-6 text-lg space-x-4">
              <div class="text-green-500">-</div>
              <p class="">
                <span class="text-green-50">Voting rights.</span> SEILOR holders
                can vote on governance proposals, influencing decisions on
                parameter adjustments, new feature additions, and protocol
                upgrades
              </p>
            </div>
            <div class="flex flex-row mt-6 text-lg space-x-4">
              <div class="text-green-500">-</div>
              <p class="">
                <span class="text-green-50">Community engagement.</span> SEILOR
                holders can engage with the community, participate in
                discussions, provide feedback, and contribute to the growth of
                the Kryptonite ecosystem
              </p>
            </div>
          </Fade>
        </div>
      </div>
    </div>
  );
}
